version: "3.8"

services:
  php-apache:
    build: .
    container_name: php-apache-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - images_data:/var/www/html/storage/images
      - ./letsencrypt:/etc/letsencrypt # SSL証明書の共有
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DB_HOST: db
      DB_USER: test
      DB_PASS: testpass
      DB_NAME: tarot_db

  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tarot_db
      MYSQL_USER: test
      MYSQL_PASSWORD: testpass

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot-container
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"

volumes:
  db_data:
  images_data: # 画像保存用のボリューム

networks:
  app-network:
