// カード情報を保持するグローバル変数
const cardData = [
  {
    id: 0,
    name: "The Fool",
    img: "./img/0_The fool.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 1,
    name: "The Magician",
    img: "./img/1_The Magus.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 2,
    name: "The Magician",
    img: "./img/2_The Priestess.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 3,
    name: "The Magician",
    img: "./img/3_The Empress.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 4,
    name: "The Magician",
    img: "./img/4_The Emperor.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 5,
    name: "The Magician",
    img: "./img/5_The Hierophant.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 6,
    name: "The Magician",
    img: "./img/6_The Lovers.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 7,
    name: "The Magician",
    img: "./img/7_The Chariot.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 8,
    name: "The Magician",
    img: "./img/8_Adjustment.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 9,
    name: "The Magician",
    img: "./img/9_The Hermit.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 10,
    name: "The Magician",
    img: "./img/10_Fortune.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 11,
    name: "The Magician",
    img: "./img/11_Lust.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 12,
    name: "The Magician",
    img: "./img/12_The Hanged Man.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 13,
    name: "The Magician",
    img: "./img/13_Death.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 14,
    name: "The Magician",
    img: "./img/14_Art.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 15,
    name: "The Magician",
    img: "./img/15_The Devil.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 16,
    name: "The Magician",
    img: "./img/16_The Tower.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 17,
    name: "The Magician",
    img: "./img/17_The Star.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 18,
    name: "The Magician",
    img: "./img/18_The Moon.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 19,
    name: "The Magician",
    img: "./img/19_The Sun.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 20,
    name: "The Magician",
    img: "./img/20_The Aeon.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
  {
    id: 21,
    name: "The World",
    img: "./img/21_The Universe.jpg",
    meaning: "カードの意味をここに入れる",
    keyword: "キーワードをここに入れる",
    description1: "今日の運勢の説明をここに入れる",
    description2: "恋占いの説明をここに入れる",
  },
];
