// カード情報を保持するグローバル変数
const cardData = [
  { id: 0, name: "The Fool", img: "./img/0_The fool.jpg" },
  { id: 1, name: "The Magician", img: "./img/1_The Magus.jpg" },
  { id: 2, name: "The Magician", img: "./img/2_The Priestess.jpg" },
  { id: 3, name: "The Magician", img: "./img/3_The Emperor.jpg" },
  { id: 4, name: "The Magician", img: "./img/4_The Emperor.jpg" },
  { id: 5, name: "The Magician", img: "./img/5_The Hierophant.jpg" },
  { id: 6, name: "The Magician", img: "./img/6_The Lovers.jpg" },
  { id: 7, name: "The Magician", img: "./img/7_The Chariot.jpg" },
  { id: 8, name: "The Magician", img: "./img/8_Adjustment.jpg" },
  { id: 9, name: "The Magician", img: "./img/9_The Hermit.jpg" },
  { id: 10, name: "The Magician", img: "./img/10_Fortune.jpg" },
  { id: 11, name: "The Magician", img: "./img/11_Lust.jpg" },
  { id: 12, name: "The Magician", img: "./img/12_The Hanged Man.jpg" },
  { id: 13, name: "The Magician", img: "./img/13_Death.jpg" },
  { id: 14, name: "The Magician", img: "./img/14_Art.jpg" },
  { id: 15, name: "The Magician", img: "./img/15_The Devil.jpg" },
  { id: 16, name: "The Magician", img: "./img/16_The Tower.jpg" },
  { id: 17, name: "The Magician", img: "./img/17_The Star.jpg" },
  { id: 18, name: "The Magician", img: "./img/18_The Moon.jpg" },
  { id: 19, name: "The Magician", img: "./img/19_The Sun.jpg" },
  { id: 20, name: "The Magician", img: "./img/20_The Aeon.jpg" },
  { id: 21, name: "The World", img: "./img/21_The world.jpg" },
];
